### ISSUE TITLE
Network change requires restart

### ISSUE THREAD

**Issue by EkiciLP** [sebadob/rauthy-pam-nss#1]
Hey,
so I use the PAM module, among others, on my laptop to provide login. Every Time I change WIFI networks it needs a restart of the rauthy-nss service to be able to resolve users again. 

The Error after providing my passkey is ``user account not found``

A solution I thought of would be to also enable offline login by caching the credentials and update them when online if that is even possible (I do not know much about the inner workings of passkeys etc.)

**Comment by sebadob** [comment]
Are you sure it's not a caching issue? By default, the nss module caches all values for 30 seconds. But this of course means that if you have an unsuccessful resolve because of a temporary network issue, it will also cache the negative response for 30 seoncds (by default).

You can test if this is the reason by simply lowering the cache time to something like 1 second. I would not set it to 0, because some commands when combined with `sudo` e.g. can trigger multiple user resolves in a very short amount of time.

Check your config in `/etc/rauthy/rauthy-pam-nss.toml`, adjust the values for `cache_ttl_*`, restart the service and see if the issue still exists.

**Comment by sebadob** [comment]
Btw offline validation / login with passkeys does not work, and that's a good thing (for security). For each authentication, the server will send a challenge, which is resolved inside the passkey with its secret key, that never even leaves the device. This is impossible to do offline.

Something like that could be implemented for password based logins, but it would be a pretty big additional attack surface, because Rauthy would need to send out password hashes to clients, which is nothing you would ever want.

**Comment by EkiciLP** [comment]
Hey, sorry for the late reply.
Changing the TTL certainly did help in some situations but I still encounter the issue for example when I connect or disconnect from a VPN the passwd table gets cleared of all rauthy users and it requires me to log in to a recovery account I thankfully created to restart rauthy-nss.

**Comment by sebadob** [comment]
The issue you are describing sounds a bit weird. the service does nothing else than a network request to Rauthy and then cache the reponse, be it positive or negative. If you have an interruption in availability, the reponse depends on the last NSS lookup.

So let's say your machine does an NSS lookup and then loses the connection before the cache expires, then you will still get the same results as before. If the lookup does not exist in the cache and you don't have a network connection, data from Rauthy will not be returned, which is of course expected.

However, the service does not clear any data, apart from when the cache expires, but thats internally in the service and does nothing on OS level. It also will work again as before if it lost the connection. The only thing coming to my mind right now is that the service maybe crashed because of something unexpected. When you have this issue, is the service still up an running when you `systemctl status rauthy-nss`, or is it crashed?
Even if it crashes, `systemd` will automatically restart it as you can see via `cat /etc/systemd/system/rauthy-nss.service`. So, even if it crashes, it should come up again automatically.

The only situation where it will (or should) stop working, is when you don't have a network connection to Rauthy of course. When this happens next time, please do the following:

- check `systemctl status rauthy-nss`
- check the log for anything weird: `tail -n 200 /var/log/rauthy/rauthy-nss.log`

Even better of course would be to live-watch the log and then reproduce the error while watching:

```bash
tail -f /var/log/rauthy/rauthy-nss.log
```

Edit:

Btw, when you are offline or the service cannot connect to Rauthy, you may get successful NSS lookups depending on the cache, but any login will not work of course, which that is to be expected. The service will never download or cache sensitive data like passwords or anything else.

**Comment by sebadob** [comment]
Oh, I may have another idea, where it could be coming from.

I not only have the cache, but also health checks implemented. When a health check fails, it will not even try to do a network request, because it can drastically degrade the NSS lookup times. This health check runs every 30 seconds. So please do another test:

If it happens again, wait ~35 seconds after the network connection has been re-established and check again without (!) restarting the service. In the worst case, the next health check after an interruption would happen 30 seconds later.

Currently, health checks are not configurable, but this can of course be an issue when you have an unstable network. It's probably a good idea to make it configurable and maybe reduce the timeout between checks after a failure down to 3 seconds or something like that.
